# Numpy Crash Course

## NumPy
NumPy (Numerical Python) is a core package for scientific computing in Python. It provides a high-performance, multidimensional array object, and tools for working with these arrays. With NumPy, you can perform efficient mathematical and logical operations on large datasets, which is essential for data analysis, machine learning, and scientific computations.

## Key Concepts in NumPy
## 1.ndarray (N-dimensional Array)

The primary object in NumPy is the ndarray, a powerful, multidimensional array structure.
Unlike Python's built-in list, NumPy arrays are homogeneous (they store elements of the same type) and are optimized for performance.
An ndarray is essentially a grid of values indexed by a tuple of non-negative integers.

## 2.Array Attributes: Arrays in NumPy have several important attributes:

Shape: Defines the dimensions of the array (e.g., for a 2D array, it could be rows and columns).

## 3.Array Creation: You can create arrays in different ways:

From Lists/Tuples: Directly convert lists or tuples to arrays

## 4.Array Indexing and Slicing:

Indexing: Access elements using indices. The index is zero-based, meaning it starts at 0.

## 5.Array Operations:

Element-wise operations: NumPy arrays allow for element-wise mathematical operations, which is much faster than using Python's built-in lists.

Universal Functions (ufuncs): NumPy includes a wide range of mathematical functions (such as np.sqrt(), np.exp(), np.log(), etc.) that operate element-wise on arrays.

## 6.Broadcasting:

Broadcasting is a powerful feature in NumPy that allows operations on arrays of different shapes and sizes.
The smaller array is "broadcast" to the shape of the larger array so they can be operated on together. This avoids the need for explicit loops.


## 7.Reshaping Arrays:

You can change the shape of an array using the reshape() method. This does not modify the data, only the way it's viewed.

## 8.Aggregations and Reductions:

NumPy provides a set of functions that allow you to compute summary statistics (e.g., sum, mean, median, etc.) and perform reductions over arrays.

Mean: Calculates the average of elements.
python
Copy
Edit


## 9.Linear Algebra:

NumPy provides a wide range of linear algebra operations (such as matrix multiplication, determinants, eigenvalues, etc.) via the np.linalg module.


## 10.Random Module:

NumPy has a random submodule to generate random numbers, shuffle data, and perform random sampling.

## 11.Masking and Conditional Indexing:

Boolean masking allows you to filter out elements from an array based on conditions.

## 12.Efficiency:

Memory efficiency: NumPy arrays are more memory-efficient than Python lists.
Performance: NumPy operations are typically faster than Python loops because NumPy operations are implemented in C and are optimized for performance.


In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

#  creating Arrays

In [8]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [10]:
type(my_list)

list

In [12]:
arr = np.array(my_list)

In [14]:
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
type(arr)

numpy.ndarray

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(3.0)

array([0., 1., 2.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [32]:
np.arange(30,20)

array([], dtype=int32)

In [34]:
b = np.arange(-20 ,20)
b

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [36]:
np.arange(10,10)

array([], dtype=int32)

In [38]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [40]:
np.arange(10,30,10)

array([10, 20])

In [42]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [44]:
np.arange(20,30,5)

array([20, 25])

In [46]:
np.arange(10,20,5,5)

TypeError: Cannot interpret '5' as a data type

In [48]:
b1 = np.zeros(10,dtype=int)
b1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
b1 = np.zeros(10,dtype =float)  #hyperparameter tunning 
b1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
zero = np.zeros((3,7))
zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [54]:
zero = np.ones((10,2))
zero

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
b1 = np.zeros(10+9,dtype=complex)
b1

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j])

In [58]:
zero

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
np.zeros((12,10))  # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [64]:
n = (5,9)
n1 = (6,10)
print(np.zeros(n))  # parameter tunnin g
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning 

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [66]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [70]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [367]:
n

(5, 9)

In [369]:
n1

(6, 10)

In [371]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [373]:
np.ones((5,9),dtype=float) # by default 5- rows & 9 - columns

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [74]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# please add new notebook & compare with np & *

In [79]:
from numpy import*
arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
range(9)
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [83]:
range(9)

range(0, 9)

In [85]:
y = list(range(9))

In [87]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [89]:
from numpy import*
zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
np.threes((3,9))

AttributeError: module 'numpy' has no attribute 'threes'

In [93]:
np.random.rand(9)

array([0.78113171, 0.31219597, 0.60378229, 0.26747552, 0.27397891,
       0.4242537 , 0.0406149 , 0.4565745 , 0.2073735 ])

In [95]:
np.random.rand(2,8)

array([[0.69419571, 0.29081374, 0.40709502, 0.61775567, 0.73545027,
        0.9266624 , 0.78001227, 0.97774683],
       [0.15151032, 0.83491688, 0.62450587, 0.04159462, 0.92164915,
        0.75981131, 0.03912169, 0.01199031]])

In [99]:
np.random.randint(5,9) # 2nd argument is exlusive 

6

In [101]:
np.random.randint(10,50,5)

array([29, 41, 10, 35, 23])

In [103]:
np.random.randint(1,3,5)

array([1, 2, 1, 2, 2])

In [105]:
np.random.randint(10,20,30)

array([18, 17, 19, 19, 18, 14, 11, 16, 16, 14, 15, 19, 16, 11, 14, 12, 17,
       18, 19, 19, 17, 13, 19, 13, 15, 10, 15, 16, 15, 16])

In [107]:
np.random.randint(90,80,60)

ValueError: low >= high

In [109]:
np.random.randint(10,21,3)

array([17, 14, 18])

In [113]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

8

In [115]:
np.random.randint(1,10,(6,10))

array([[6, 9, 2, 5, 3, 9, 1, 1, 2, 3],
       [5, 4, 5, 9, 2, 4, 3, 8, 7, 5],
       [3, 8, 7, 7, 3, 4, 7, 1, 8, 9],
       [3, 6, 9, 3, 8, 1, 4, 3, 4, 6],
       [6, 9, 2, 7, 5, 2, 4, 3, 9, 5],
       [4, 5, 8, 5, 2, 6, 1, 4, 9, 1]])

In [117]:
np.random.rand(20,30)

array([[2.59693198e-01, 8.98503736e-01, 4.45456717e-01, 2.48529591e-02,
        6.94596626e-02, 7.28622066e-01, 6.77227241e-02, 3.03241468e-01,
        8.91434547e-01, 3.68757053e-01, 5.74060546e-01, 3.00302250e-01,
        7.04003297e-01, 9.27296549e-01, 9.61794086e-01, 4.23587039e-01,
        4.92002183e-01, 8.50987053e-01, 7.60967376e-01, 9.50339461e-01,
        9.51444790e-01, 9.81612210e-02, 3.55432894e-01, 9.24002532e-01,
        8.18739948e-01, 5.90514969e-01, 6.06013720e-01, 6.56138422e-01,
        6.39188577e-01, 7.57896923e-01],
       [1.63838222e-01, 9.02621011e-01, 6.33685933e-01, 7.55646135e-01,
        8.25156849e-01, 6.51360823e-02, 6.97722834e-01, 8.39148217e-01,
        7.88868080e-02, 5.32881898e-01, 9.56672258e-01, 8.96158358e-02,
        2.15103630e-01, 4.17132413e-01, 5.61307069e-01, 5.75983920e-02,
        5.91714875e-01, 4.20079349e-01, 6.12362911e-02, 9.18778875e-01,
        6.52576381e-01, 7.38582437e-02, 9.48743718e-02, 6.32611543e-01,
        8.98143141e-02,

In [119]:
np.random.rand(9,9)

array([[0.3519976 , 0.04345955, 0.23739889, 0.33269728, 0.40624925,
        0.97095133, 0.47725833, 0.59637629, 0.73076017],
       [0.90320359, 0.24914435, 0.67432342, 0.20192022, 0.67201608,
        0.13516271, 0.28642754, 0.77295581, 0.53908426],
       [0.2613774 , 0.91376424, 0.80599482, 0.99225142, 0.41482354,
        0.5554168 , 0.61219359, 0.61553877, 0.66972868],
       [0.28689069, 0.3407645 , 0.75145562, 0.04349142, 0.32264622,
        0.10134876, 0.80221172, 0.47833291, 0.35348699],
       [0.35053566, 0.66800726, 0.01077699, 0.17193577, 0.55107729,
        0.19045068, 0.05664063, 0.9133506 , 0.73718949],
       [0.80320806, 0.48714694, 0.57298415, 0.36055712, 0.5527174 ,
        0.02895492, 0.67203206, 0.36494305, 0.87618376],
       [0.78403116, 0.00808515, 0.63526285, 0.97388892, 0.21658915,
        0.92000561, 0.18802338, 0.51093245, 0.67964887],
       [0.45381064, 0.0787703 , 0.64081797, 0.55610506, 0.18025371,
        0.84828187, 0.64303045, 0.24387714, 0.90345783],


In [411]:
np.random.randint(0,5)

1

In [121]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[10, 18, 13, 10, 29, 19, 35, 11, 39, 35],
       [17, 32, 11, 20, 34, 29, 32, 39, 29, 39],
       [32, 36, 15, 21, 36, 17, 33, 35, 20, 25],
       [26, 15, 25, 25, 27, 12, 29, 12, 15, 28],
       [11, 32, 20, 37, 12, 31, 21, 22, 39, 29],
       [10, 37, 27, 24, 17, 33, 35, 15, 24, 15],
       [39, 12, 14, 36, 35, 36, 21, 39, 12, 30],
       [12, 29, 21, 15, 21, 27, 24, 29, 38, 14],
       [10, 18, 15, 16, 31, 11, 16, 38, 34, 12],
       [17, 28, 28, 20, 38, 14, 12, 30, 24, 26]])

In [123]:
np.random.randint(9,77)

73

In [125]:
np.random. randint(0,2)

0

In [127]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 17, 12, 16],
       [10, 12, 19, 16],
       [12, 16, 16, 19],
       [10, 10, 16, 15],
       [11, 11, 19, 19]])

In [129]:
b[:]

array([[12, 17, 12, 16],
       [10, 12, 19, 16],
       [12, 16, 16, 19],
       [10, 10, 16, 15],
       [11, 11, 19, 19]])

In [131]:
b[0:2]

array([[12, 17, 12, 16],
       [10, 12, 19, 16]])

In [133]:
b

array([[12, 17, 12, 16],
       [10, 12, 19, 16],
       [12, 16, 16, 19],
       [10, 10, 16, 15],
       [11, 11, 19, 19]])

In [135]:
b[0:-1]

array([[12, 17, 12, 16],
       [10, 12, 19, 16],
       [12, 16, 16, 19],
       [10, 10, 16, 15]])

In [137]:
np.random.randint(10)

6

In [139]:
np.random.randint(1,2,3)

array([1, 1, 1])

In [141]:
np.random.randint(11,15,3)

array([13, 14, 12])

In [143]:
np.random.randint(9,36,(11,5))

array([[20, 35, 19, 23, 28],
       [22, 15, 28, 17, 28],
       [29, 29, 19, 27, 19],
       [12, 18, 17, 35, 22],
       [14, 16, 15, 29, 16],
       [19, 14, 16, 21, 30],
       [25, 33, 26, 23, 29],
       [18, 26, 31, 14, 19],
       [34, 23, 17, 22, 19],
       [24, 21, 31, 16, 19],
       [18, 34, 32, 17, 26]])

In [145]:
b = np.random.randint(8,20,(9,5))
b

array([[14, 19, 14, 17, 10],
       [14,  9, 10, 16,  9],
       [19, 10, 11, 18, 12],
       [19, 15, 12, 19,  8],
       [15, 11, 15, 17, 15],
       [12, 18, 18, 15, 14],
       [17, 16, 10, 17, 16],
       [18,  9, 18,  8, 14],
       [19, 17, 10, 13, 19]])

In [147]:
b[:]

array([[14, 19, 14, 17, 10],
       [14,  9, 10, 16,  9],
       [19, 10, 11, 18, 12],
       [19, 15, 12, 19,  8],
       [15, 11, 15, 17, 15],
       [12, 18, 18, 15, 14],
       [17, 16, 10, 17, 16],
       [18,  9, 18,  8, 14],
       [19, 17, 10, 13, 19]])

In [149]:
b[2:9]

array([[19, 10, 11, 18, 12],
       [19, 15, 12, 19,  8],
       [15, 11, 15, 17, 15],
       [12, 18, 18, 15, 14],
       [17, 16, 10, 17, 16],
       [18,  9, 18,  8, 14],
       [19, 17, 10, 13, 19]])

In [151]:
b[0:4]

array([[14, 19, 14, 17, 10],
       [14,  9, 10, 16,  9],
       [19, 10, 11, 18, 12],
       [19, 15, 12, 19,  8]])

In [153]:
b[4:6]

array([[15, 11, 15, 17, 15],
       [12, 18, 18, 15, 14]])

In [155]:
b

array([[14, 19, 14, 17, 10],
       [14,  9, 10, 16,  9],
       [19, 10, 11, 18, 12],
       [19, 15, 12, 19,  8],
       [15, 11, 15, 17, 15],
       [12, 18, 18, 15, 14],
       [17, 16, 10, 17, 16],
       [18,  9, 18,  8, 14],
       [19, 17, 10, 13, 19]])

In [157]:
b[0,4]

10

In [159]:
b[-2,-4]

9

In [161]:
b[-4,-5]

12

#  OPERATIONS

In [166]:
a = np.random.randint(10,20,5)
a

array([14, 10, 12, 15, 16])

In [168]:
arr

array([0, 1, 2, 3, 4, 5])

In [170]:
arr2 = np.random.randint(0,100,(10,10))

In [172]:
arr2

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [36, 75, 43, 38, 19, 62, 11, 83, 18, 72]])

In [174]:
arr

array([0, 1, 2, 3, 4, 5])

In [176]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [178]:
arr[:4]

array([0, 1, 2, 3])

In [180]:
arr2[:]

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [36, 75, 43, 38, 19, 62, 11, 83, 18, 72]])

In [182]:
arr2[0:5]

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89]])

In [184]:
arr2

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [36, 75, 43, 38, 19, 62, 11, 83, 18, 72]])

In [186]:
arr2[1,5]

83

In [188]:
arr2

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [36, 75, 43, 38, 19, 62, 11, 83, 18, 72]])

In [190]:
arr2[-5,5]

71

In [192]:
arr2[-5,-5]

71

In [194]:
arr2

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [36, 75, 43, 38, 19, 62, 11, 83, 18, 72]])

In [196]:
arr2[-5,-5]

71

In [198]:
arr2

array([[23, 74, 41, 46,  2, 89, 44, 64, 24, 43],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [36, 75, 43, 38, 19, 62, 11, 83, 18, 72]])

In [200]:
arr2[-1,-2]

18

In [202]:
arr2[::-1]

array([[36, 75, 43, 38, 19, 62, 11, 83, 18, 72],
       [77, 84, 50,  5, 94, 76, 48, 41, 74, 23],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [27, 49, 17, 26, 22, 66, 94, 33, 57, 89],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [82, 12, 29, 83, 79, 36,  2, 65, 97, 45],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54],
       [23, 74, 41, 46,  2, 89, 44, 64, 24, 43]])

In [204]:
arr2[::-2]

array([[36, 75, 43, 38, 19, 62, 11, 83, 18, 72],
       [17, 85, 99, 22, 26, 39, 11, 42, 33, 90],
       [32,  4, 69, 29, 86, 71, 10, 55, 63, 42],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [85,  0, 20, 45, 50, 83, 72, 27, 66, 54]])

In [206]:
arr2[::-3]

array([[36, 75, 43, 38, 19, 62, 11, 83, 18, 72],
       [51,  1, 85, 40, 29, 83, 35, 50, 61, 23],
       [92, 23, 95, 68, 78, 50, 28, 41,  3, 37],
       [23, 74, 41, 46,  2, 89, 44, 64, 24, 43]])

In [212]:
arr

array([0, 1, 2, 3, 4, 5])

In [214]:
arr.max() 

5

In [216]:
arr.min()

0

In [218]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [220]:
arr

array([0, 1, 2, 3, 4, 5])

In [222]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [224]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [226]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [228]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [230]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [232]:
arr.reshape(3,2,order='F') 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [234]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [236]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [238]:
arr.reshape(6,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [240]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [242]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [244]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [255]:
mat = np.arange(0,200).reshape(20,10)

In [257]:
mat

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [259]:
row = 4
col = 5

In [261]:
col

5

In [263]:
row

4

In [265]:
mat

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [267]:
mat[row,col] 

45

In [269]:
mat[4,5] 

45

In [271]:
mat

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [273]:
mat[:]

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [279]:
col = 7

In [281]:
mat

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [283]:
# With Slices
mat[:,col] 

array([  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107, 117, 127,
       137, 147, 157, 167, 177, 187, 197])

In [285]:
mat

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [287]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [289]:
mat[:,col]

array([  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107, 117, 127,
       137, 147, 157, 167, 177, 187, 197])

In [291]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [293]:
mat

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [297]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [299]:
mat[row:] 

array([[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [301]:
mat[:,8] 

array([  8,  18,  28,  38,  48,  58,  68,  78,  88,  98, 108, 118, 128,
       138, 148, 158, 168, 178, 188, 198])

In [303]:
mat[:,-1] 

array([  9,  19,  29,  39,  49,  59,  69,  79,  89,  99, 109, 119, 129,
       139, 149, 159, 169, 179, 189, 199])

In [305]:
mat[:,col]

array([  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107, 117, 127,
       137, 147, 157, 167, 177, 187, 197])

In [307]:
mat[1,4]

14

In [311]:
mat[3:-5]

array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]])

In [313]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [315]:
mat[6:]

array([[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [317]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [319]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [321]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [323]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [325]:
mat[4:]

array([[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [327]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [329]:
mat[::-1]

array([[190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39

In [331]:
mat[::-2]

array([[190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]])

In [333]:
mat[::-5]

array([[190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [335]:
mat[::-5]

array([[190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [337]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [339]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [341]:
mat[1:2,2:4]

array([[12, 13]])

In [343]:
mat[2:3,2:3]

array([[22]])

In [345]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [347]:
mat[2:3,4:5]

array([[24]])

## Masking

In [350]:
mat # we also called as filter

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [352]:
id(mat)

1688032255056

In [354]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

In [356]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, 

In [358]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

In [360]:
mat[mat==50]

array([50])

In [362]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [364]:
a2 = mat[mat>50] 
a2

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,
       194, 195, 196, 197, 198, 199])

In [366]:
a3 = mat[mat>=50] 
a3

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199])

In [368]:
a4 = mat[mat==50]
a4

array([50])

In [370]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [372]:
a2

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,
       194, 195, 196, 197, 198, 199])